version: '3.4'

services:
  authenticationapi:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
        context: .
        dockerfile: AuthenticationApi/Dockerfile
    networks:
    - backend-net

  serverslotapi:
    container_name:   serverslotapi-api
    image: ${DOCKER_REGISTRY-}serverslotapi
    build:
      context: .
      dockerfile: ServerSlotApi/Dockerfile
    networks:
    - backend-net

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports: 
      - 7129:8081
    networks:
      - backend-net
    depends_on:
    - authenticationapi
    - serverslotapi

networks:
  backend-net: