version: '3.4'

services:
  authenticationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AuthenticationConnection=${ConnectionStrings__AuthenticationConnection}
      - EFCreateDatabase=${EFCreateDatabase}
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__RefreshExpiryInDays=${AuthSettings__RefreshExpiryInDays}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro