version: '3.4'

services:
  controller-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_LISTENERS: "CONTROLLER://controller-1:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "GLZOVd8vSKuXdgAApudsAg"
    networks:
      - backend-net

  broker-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker-1
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-1:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://broker-1:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "GLZOVd8vSKuXdgAApudsAg"
    networks:
      - backend-net

networks:
  backend-net: