version: '3.4'

services:
  authenticationapi:
    container_name: serverpulse-authentication-api
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
        context: .
        dockerfile: AuthenticationApi/Dockerfile
    networks:
    - backend-net

  serverslotapi:
    container_name: serverpulse-serverslot-api
    image: ${DOCKER_REGISTRY-}serverslotapi
    build:
      context: .
      dockerfile: ServerSlotApi/Dockerfile
    networks:
    - backend-net

  serverinteractionapi:
    container_name: serverpulse-serverinteraction-api
    image: ${DOCKER_REGISTRY-}serverinteractionapi
    build:
      context: .
      dockerfile: ServerInteractionApi/Dockerfile
    networks:
    - backend-net
  
  analyzerapi:
    container_name: serverpulse-analyzer-api
    image: ${DOCKER_REGISTRY-}analyzerapi
    build:
      context: .
      dockerfile: AnalyzerApi/Dockerfile
    networks:
    - backend-net

  apigateway:
    container_name: serverpulse-apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports: 
      - 7129:8081
    networks:
      - backend-net
    depends_on:
    - authenticationapi
    - serverslotapi
    - serverinteractionapi
    - analyzerapi

networks:
  backend-net: