# Db
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: server-pulse
  name: db-app
  labels:
    app: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db-app
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: db-secret
          resources:
            requests:
              memory: "512M"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "750m"
              ephemeral-storage: "2Gi"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
      automountServiceAccountToken: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: server-pulse
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: db-svc
spec:
  type: NodePort
  selector:
    app: db-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007
---
# Redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: server-pulse
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis-app
          image: redis:7.4
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "512M"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "750m"
              ephemeral-storage: "2Gi"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
      automountServiceAccountToken: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: server-pulse
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: redis-svc
spec:
  selector:
    app: redis-app
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
