version: '3.4'

services:
  serverpulse-db:
    container_name: serverpulse-db
    image: postgres
    restart: always
    ports:
    - "54303:5432"
    networks:
    - backend-net
    volumes:
    - ./init_history.sql:/docker-entrypoint-initdb.d/init_history.sql
    - serverpulse-db:/var/lib/postgresql/data
  serverslotcheck-redis:
    container_name: serverpulse-serverslotcheck-redis
    image: redis:latest
    ports:
    - "6380:6379"
    networks:
    - backend-net
    volumes:
    - serverpulse-serverslotcheck-redis:/data

volumes:
  serverpulse-db:
  serverpulse-serverslotcheck-redis:

networks:
  backend-net: