version: '3.4'

services:
  authenticationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AuthenticationDb=${ConnectionStrings__AuthenticationDb}
      - EFCreateDatabase=${EFCreateDatabase}
      - AuthSettings__PublicKey=${AuthSettings__PublicKey}
      - AuthSettings__PrivateKey=${AuthSettings__PrivateKey}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AuthSettings__RefreshExpiryInDays=${AuthSettings__RefreshExpiryInDays}
      - AuthSettings__GoogleOAuth__ClientId=${AuthSettings__GoogleOAuth__ClientId}
      - AuthSettings__GoogleOAuth__ClientSecret=${AuthSettings__GoogleOAuth__ClientSecret}
      - AuthSettings__GoogleOAuth__Scope=${AuthSettings__GoogleOAuth__Scope}
      - FeatureManagement__RequireEmailConfirmation=${FeatureManagement__RequireEmailConfirmation}
      - Email__ConnectionString=${Email__ConnectionString}
      - Email__SenderAddress=${Email__SenderAddress}
      - UnconfirmedUsersCleanUpInMinutes=${UnconfirmedUsersCleanUpInMinutes}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  serverslotapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - EFCreateDatabase=${EFCreateDatabase}
      - ConnectionStrings__ServerSlotDb=${ConnectionStrings__ServerSlotDb}
      - SlotsPerUser=${SlotsPerUser}
      - AuthSettings__PublicKey=${AuthSettings__PublicKey}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - ConnectionStrings__RedisServer=${ConnectionStrings__RedisServer}
      - Cache__GetServerSlotByEmailExpiryInSeconds=${Cache__GetServerSlotByEmailExpiryInSeconds}
      - Cache__ServerSlotCheckExpiryInSeconds=${Cache__ServerSlotCheckExpiryInSeconds}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  servermonitorapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Kafka__ClientId=${Kafka__ClientId__MonitorApi}
      - Kafka__BootstrapServers=${Kafka__BootstrapServers}
      - Kafka__AliveTopic=${Kafka__AliveTopic}
      - Kafka__ConfigurationTopic=${Kafka__ConfigurationTopic}
      - Kafka__LoadTopic=${Kafka__LoadTopic}
      - Kafka__LoadTopicProcess=${Kafka__LoadTopicProcess}
      - Kafka__CustomTopic=${Kafka__CustomTopic}
      - ServerSlotApi__Url=${ApiGateway}
      - ServerSlotApi__Check=${ServerSlotApi__Check}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  analyzerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Kafka__BootstrapServers=${Kafka__BootstrapServers}
      - Kafka__ClientId=${Kafka__ClientId__Analyzer}
      - Kafka__GroupId=${Kafka__GroupId}
      - Kafka__ReceiveTimeoutInMilliseconds=${Kafka__ReceiveTimeoutInMilliseconds}
      - Kafka__AliveTopic=${Kafka__AliveTopic}
      - Kafka__ConfigurationTopic=${Kafka__ConfigurationTopic}
      - Kafka__LoadTopic=${Kafka__LoadTopic}
      - Kafka__CustomTopic=${Kafka__CustomTopic}
      - Kafka__LoadMethodStatisticsTopic=${Kafka__LoadMethodStatisticsTopic}
      - Kafka__LoadTopicProcess=${Kafka__LoadTopicProcess}
      - Kafka__ServerStatisticsTopic=${Kafka__ServerStatisticsTopic}
      - Kafka__TopicDataSaveInDays=${Kafka__TopicDataSaveInDays}
      - PulseEventIntervalInMilliseconds=${PulseEventIntervalInMilliseconds}
      - StatisticsCollectIntervalInMilliseconds=${StatisticsCollectIntervalInMilliseconds}
      - ConnectionStrings__RedisServer=${ConnectionStrings__RedisServer}
      - Cache__ExpiryInMinutes=${Cache__ExpiryInMinutes}
      - MinimumStatisticsTimeSpanInSeconds=${MinimumStatisticsTimeSpanInSeconds}
      - MaxEventAmountToGetInSlotData=${MaxEventAmountToGetInSlotData}
      - MaxEventAmountToReadPerRequest=${MaxEventAmountToReadPerRequest}
      - LoadEventProcessing__BatchSize=${LoadEventProcessing__BatchSize}
      - LoadEventProcessing__BatchIntervalInMilliseconds=${LoadEventProcessing__BatchIntervalInMilliseconds}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;https://+:8081;
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertificatePassword}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
      - AuthSettings__PublicKey=${AuthSettings__PublicKey}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AllowedCORSOrigins=${AllowedCORSOrigins}
      - UseCORS=${UseCORS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro