version: '3.4'

services:
  redis-node-1:
    container_name: serverpulse-redis-node-1
    image: redis:7.4
    # command: ["redis-server", "/redis/redis.conf"]
    networks:
      - backend-net
    # volumes:
    #   - ./redis.conf:/redis/redis.conf

  # redis-node-2:
  #   container_name: serverpulse-redis-node-2
  #   image: redis:7.4
  #   command: ["redis-server", "/redis/redis.conf"]
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./redis.conf:/redis/redis.conf

  # redis-node-3:
  #   container_name: serverpulse-redis-node-3
  #   image: redis:7.4
  #   command: ["redis-server", "/redis/redis.conf"]
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./redis.conf:/redis/redis.conf

  # redis-node-4:
  #   container_name: serverpulse-redis-node-4
  #   image: redis:7.4
  #   command: ["redis-server", "/redis/redis.conf"]
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./redis.conf:/redis/redis.conf

  # redis-node-5:
  #   container_name: serverpulse-redis-node-5
  #   image: redis:7.4
  #   command: ["redis-server", "/redis/redis.conf"]
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./redis.conf:/redis/redis.conf

  # redis-node-6:
  #   container_name: serverpulse-redis-node-6
  #   image: redis:7.4
  #   command: ["redis-server", "/redis/redis.conf"]
  #   networks:
  #     - backend-net
  #   volumes:
  #     - ./redis.conf:/redis/redis.conf

  # redis-cluster-creator:
  #   container_name: serverpulse-redis-cluster-creator-1
  #   image: redis:7.4
  #   entrypoint: ["sh", "-c", "sleep 20 && redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1 --cluster-yes"]
  #   networks:
  #     - backend-net
  #   depends_on:
  #     - redis-node-1
  #     - redis-node-2
  #     - redis-node-3
  #     - redis-node-4
  #     - redis-node-5
  #     - redis-node-6

networks:
  backend-net: