#API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-pulse
  name: apigateway-app
  labels:
    app: apigateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-app
  template:
    metadata:
      labels:
        app: apigateway-app
    spec:
      containers:
        - name: apigateway-app
          image: tegto/serverpulse.apigateway:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
---
#Authentication Api
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-pulse
  name: authenticationapi-app
  labels:
    app: authenticationapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapi-app
  template:
    metadata:
      labels:
        app: authenticationapi-app
    spec:
      containers:
        - name: authenticationapi-app
          image: tegto/serverpulse.authenticationapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: authenticationapi
spec:
  selector:
    app: authenticationapi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#Analyzer Api
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-pulse
  name: analyzerapi-app
  labels:
    app: analyzerapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzerapi-app
  template:
    metadata:
      labels:
        app: analyzerapi-app
    spec:
      containers:
        - name: analyzerapi-app
          image: tegto/serverpulse.analyzerapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: analyzerapi
spec:
  selector:
    app: analyzerapi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#Server Monitor Api
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-pulse
  name: servermonitorapi-app
  labels:
    app: servermonitorapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servermonitorapi-app
  template:
    metadata:
      labels:
        app: servermonitorapi-app
    spec:
      containers:
        - name: servermonitorapi-app
          image: tegto/serverpulse.servermonitorapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: servermonitorapi
spec:
  selector:
    app: servermonitorapi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#Server Slot Api
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-pulse
  name: serverslotapi-app
  labels:
    app: serverslotapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverslotapi-app
  template:
    metadata:
      labels:
        app: serverslotapi-app
    spec:
      containers:
        - name: serverslotapi-app
          image: tegto/serverpulse.serverslotapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: server-pulse
  name: serverslotapi
spec:
  selector:
    app: serverslotapi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

